camel:
  server-port: 5000
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true

server:
  port: 8080

zeebe:
  client:
    max-execution-threads: 1000
    evenly-allocated-max-jobs: 1000
#    max-execution-threads: 100
#    number-of-workers: 8
#    evenly-allocated-max-jobs: "#{${zeebe.client.max-execution-threads} / ${zeebe.client.number-of-workers}}"
  broker:
    contactpoint: "127.0.0.1:26500"

#ams:
#  local:
#    server-cert-check: false
#    enabled: true

ams:
  local:
    enabled: true
    tenants:
      - name: "gorilla"
        user: mifos
        password: password
        authtype: basic
        fspId: in02tn03
      - name: "rhino"
        user: mifos
        password: password
        authtype: basic
        fspId: in02tn04
    server-cert-check: false

interop-party-registration:
  enabled: false

accountPrefixes: "S,L"

